using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Anis.Partners.Sdk.Enrollment;
using Anis.Partners.Sdk.Errors;
using Anis.Partners.Sdk.Models;
using Anis.Partners.Sdk.Observability;
using Anis.Partners.Sdk.Verification;

namespace Anis.Partners.Sdk.Tests;

/// <summary>Enrollment: the possession proof Anis verifies, and the walk from invitation to proof.</summary>
/// <remarks>
/// The proof vectors were generated by the conformance tool and cross-validated against COMMANDS' own
/// <c>ProofVerification</c> — the code that decides whether a proof is accepted — so a failure here means
/// the SDK no longer proves possession in the form Anis verifies.
/// </remarks>
public sealed class EnrollmentTests
{
    private const string ResponseKeyId = "partner-response-signing/v1-active";
    private const string Token = "enrollment-token-7Qm2Xv9Lp4Rk8Tz1Wc6Nb3Hs5Jd0Fg";

    private static readonly Guid Invitation = Guid.Parse("3f2a9c14-8d6e-4b21-9f07-5c8ab2d61e43");
    private static readonly DateTimeOffset Now = DateTimeOffset.FromUnixTimeSeconds(1789804800);

    public static TheoryData<string> Vectors
    {
        get
        {
            var directory = Path.Combine(AppContext.BaseDirectory, "vectors", "enrollment");

            var files = Directory.Exists(directory)
                ? Directory.GetFiles(directory, "EP-*.json").Order(StringComparer.Ordinal).ToArray()
                : [];

            Assert.True(files.Length > 0, $"No enrollment proof vectors were found under {directory}.");

            return new TheoryData<string>(files);
        }
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public async Task The_sdk_builds_the_proof_Commands_verifies(string path)
    {
        var vector = JsonDocument.Parse(await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken)).RootElement;
        var result = vector.GetProperty("keySubmissionResult");
        var expected = vector.GetProperty("expected");

        var submitted = new EnrollmentKeyResult
        {
            KeyId = Guid.Parse(result.GetProperty("keyId").GetString()!),
            Thumbprint = result.GetProperty("thumbprint").GetString(),
            Challenge = result.GetProperty("challenge").GetString(),
            ChallengeGeneration = result.GetProperty("challengeGeneration").GetInt32(),
        };

        // The message is deterministic: byte for byte what Anis rebuilds.
        var message = AnisEnrollmentClient.ProofMessage(submitted);

        Assert.Equal(expected.GetProperty("proofMessageBase64").GetString(), Convert.ToBase64String(message));

        using var key = ECDsa.Create();
        key.ImportPkcs8PrivateKey(Convert.FromBase64String(vector.GetProperty("key").GetProperty("privateKeyPkcs8Base64").GetString()!), out _);

        var proof = AnisEnrollmentClient.CreateProof(submitted, key);

        // The signature differs every run; its form and its validity do not.
        Assert.Equal(submitted.KeyId, proof.KeyId);
        Assert.Equal(submitted.ChallengeGeneration, proof.ChallengeGeneration);
        Assert.Equal(86, proof.Signature.Length);
        Assert.DoesNotContain('=', proof.Signature);
        Assert.DoesNotContain('+', proof.Signature);
        Assert.DoesNotContain('/', proof.Signature);

        Assert.True(Verifies(key, message, proof.Signature), "The SDK's proof does not verify over Anis's message.");
        Assert.True(Verifies(key, message, vector.GetProperty("exampleSignature").GetString()!), "The vector's example proof does not verify.");
    }

    [Fact]
    public void A_der_signature_is_refused_before_it_reaches_Anis()
    {
        using var key = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var submitted = Submitted();

        var der = key.SignData(AnisEnrollmentClient.ProofMessage(submitted), HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence);

        Assert.Throws<ArgumentException>(() => AnisEnrollmentClient.CreateProof(submitted, der));
    }

    [Fact]
    public void A_key_on_another_curve_is_refused()
    {
        using var key = ECDsa.Create(ECCurve.NamedCurves.nistP384);

        Assert.Throws<ArgumentException>(() => AnisEnrollmentClient.CreateProof(Submitted(), key));
    }

    [Fact]
    public void A_submission_result_without_its_challenge_cannot_be_proved()
        => Assert.Throws<ArgumentException>(() => AnisEnrollmentClient.ProofMessage(Submitted() with { Challenge = null }));

    [Fact]
    public async Task Submit_then_prove_walks_the_enrollment_routes_and_verifies_every_answer()
    {
        using var responseKey = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        using var partnerKey = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        using var capture = new TelemetryCapture();

        var stub = new SignedResponseStub(responseKey, ResponseKeyId) { SignedAt = Now, NoStore = true };

        stub.Bodies.Enqueue($$"""{"keyId":"{{Invitation:D}}","thumbprint":"sT9pY2vQ4mW7nK1xR8cL3hB6fJ0dG5aZ2eU9oI4tN7w","challenge":"tX3vQ9m2Lr8Kc4Hw1Zp7Ns0Ye6Ud5Jb2Gf9Aq3Vk8Mo","challengeGeneration":1}""");
        stub.Bodies.Enqueue($$"""{"keyId":"{{Invitation:D}}","challengeGeneration":1,"proofState":"accepted","approvalState":"pending","state":"pendingApproval"}""");

        using var enrollment = AnisEnrollmentClient.Create(
            new Uri("https://partners.anis.ly"), Invitation, Token, KeysFor(responseKey), stub, new FixedClock(Now));

        var submitted = await enrollment.SubmitKeyAsync(
            new EnrollmentKeyRequest
            {
                PublicJwk = AnisEnrollmentClient.PublicJwkOf(partnerKey),
                NotBefore = Now,
                ExpiresAt = Now.AddYears(1),
                Cidrs = ["203.0.113.0/24"],
            },
            TestContext.Current.CancellationToken);

        var status = await enrollment.ProveAsync(submitted, partnerKey, TestContext.Current.CancellationToken);

        Assert.Equal("pendingApproval", status.State);
        Assert.Equal("accepted", status.ProofState);

        // Two requests, both on the enrollment branch: the token, and no message signature at all.
        Assert.Equal(2, stub.Requests.Count);
        Assert.All(stub.Requests, request =>
        {
            Assert.Equal($"Enrollment {Token}", request.Headers.GetValues("Authorization").Single());
            Assert.False(request.Headers.Contains("Signature"));
        });

        Assert.Equal($"/v1/enrollments/{Invitation:D}/keys", stub.Requests[0].RequestUri!.AbsolutePath);
        Assert.Equal($"/v1/enrollments/{Invitation:D}/proof", stub.Requests[1].RequestUri!.AbsolutePath);

        // The proof that went out is the one Anis verifies.
        var sent = JsonDocument.Parse(stub.LastRequestBody!).RootElement;

        Assert.Equal(Invitation.ToString("D"), sent.GetProperty("keyId").GetString());
        Assert.Equal(1, sent.GetProperty("challengeGeneration").GetInt32());
        Assert.True(Verifies(partnerKey, AnisEnrollmentClient.ProofMessage(submitted), sent.GetProperty("signature").GetString()!));

        // The key submission carried the PUBLIC half only.
        Assert.DoesNotContain("\"d\"", Encoding.UTF8.GetString(stub.RequestBodies[0]!), StringComparison.Ordinal);

        // The token is a secret: on no span, log or metric.
        Assert.NotEmpty(capture.Spans);
        Assert.DoesNotContain(Token, capture.Everything, StringComparison.Ordinal);
    }

    [Fact]
    public async Task A_refused_step_is_an_enrollment_exception()
    {
        using var responseKey = ECDsa.Create(ECCurve.NamedCurves.nistP256);

        var stub = new SignedResponseStub(responseKey, ResponseKeyId)
        {
            SignedAt = Now,
            NoStore = true,
            Status = HttpStatusCode.Conflict,
            Body = """{"type":"https://developers.anis.ly/errors/challenge-expired","title":"t","status":409,"code":"challenge_expired"}""",
        };

        using var enrollment = AnisEnrollmentClient.Create(
            new Uri("https://partners.anis.ly"), Invitation, Token, KeysFor(responseKey), stub, new FixedClock(Now));

        var failure = await Assert.ThrowsAsync<EnrollmentRefusedException>(
            () => enrollment.SubmitProofAsync(
                new EnrollmentProofRequest { KeyId = Invitation, ChallengeGeneration = 1, Signature = new string('A', 86) },
                TestContext.Current.CancellationToken));

        Assert.Equal(PartnerErrorCode.ChallengeExpired, failure.Code);
    }

    [Fact]
    public async Task An_enrollment_call_is_measured_like_every_other_call()
    {
        using var responseKey = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        using var capture = new TelemetryCapture();

        var stub = new SignedResponseStub(responseKey, ResponseKeyId)
        {
            SignedAt = Now,
            NoStore = true,
            Body = $$"""{"invitationId":"{{Invitation:D}}","state":"pendingPublicKey"}""",
        };

        using var enrollment = AnisEnrollmentClient.Create(
            new Uri("https://partners.anis.ly"), Invitation, Token, KeysFor(responseKey), stub, new FixedClock(Now));

        var state = await enrollment.GetAsync(TestContext.Current.CancellationToken);

        Assert.Equal("pendingPublicKey", state.State);

        // The shared transport measures the enrollment call under its route template; the token is on no signal.
        var duration = Assert.Single(capture.Measurements, m => m.Instrument == "anis.partners.request.duration");
        Assert.Equal("default", duration.Tags[AnisPartnersTelemetry.Tags.Client]);
        Assert.Equal("/v1/enrollments/{invitationId}", duration.Tags[AnisPartnersTelemetry.Tags.Route]);
        Assert.Equal("GET", duration.Tags[AnisPartnersTelemetry.Tags.Method]);
        Assert.Equal("200", duration.Tags[AnisPartnersTelemetry.Tags.StatusCode]);
        Assert.DoesNotContain(Token, capture.Everything, StringComparison.Ordinal);
        Assert.Equal($"Enrollment {Token}", stub.LastRequest!.Headers.GetValues("Authorization").Single());
        Assert.Equal($"/v1/enrollments/{Invitation:D}", stub.LastRequest.RequestUri!.AbsolutePath);
        Assert.False(stub.LastRequest!.Headers.Contains("Signature"));
        Assert.False(stub.LastRequest.Headers.Contains("Signature-Input"));
    }

    private static EnrollmentKeyResult Submitted() => new()
    {
        KeyId = Invitation,
        Thumbprint = "sT9pY2vQ4mW7nK1xR8cL3hB6fJ0dG5aZ2eU9oI4tN7w",
        Challenge = "tX3vQ9m2Lr8Kc4Hw1Zp7Ns0Ye6Ud5Jb2Gf9Aq3Vk8Mo",
        ChallengeGeneration = 1,
    };

    private static bool Verifies(ECDsa key, byte[] message, string base64Url)
    {
        var padded = base64Url.Replace('-', '+').Replace('_', '/');
        padded = padded.PadRight(padded.Length + ((4 - (padded.Length % 4)) % 4), '=');

        return key.VerifyData(message, Convert.FromBase64String(padded), HashAlgorithmName.SHA256, DSASignatureFormat.IeeeP1363FixedFieldConcatenation);
    }

    private static StaticSigningKeySource KeysFor(ECDsa responseKey)
    {
        var point = responseKey.ExportParameters(includePrivateParameters: false).Q;

        return new StaticSigningKeySource(new PartnerSigningKeySet
        {
            Keys = [new PartnerJwk { Kty = "EC", Crv = "P-256", Kid = ResponseKeyId, X = Encode(point.X!), Y = Encode(point.Y!) }],
        });
    }

    private static string Encode(byte[] value) => Convert.ToBase64String(value).TrimEnd('=').Replace('+', '-').Replace('/', '_');

    private sealed class FixedClock(DateTimeOffset now) : TimeProvider
    {
        public override DateTimeOffset GetUtcNow() => now;
    }
}
