namespace Anis.Partners.Sdk.Signing;

/// <summary>How an operation tells the signing handler which profile a request uses.</summary>
/// <remarks>
/// The profile is carried on the request rather than inferred from the method or the URL. Inferring it
/// would mean the SDK holds a second copy of the route map — and a second copy of a closed map is a copy
/// that drifts. The operations layer knows which route it is calling and says so.
/// </remarks>
internal static class PartnerRequestOptions
{
    /// <summary>The covered-component profile this request signs under.</summary>
    public static readonly HttpRequestOptionsKey<SignatureProfile> Profile = new("anis.partners.profile");

    /// <summary>The caller-owned operation identity, on the order profile only.</summary>
    /// <remarks>
    /// Supplied by the caller and never generated by the SDK. An SDK-minted key turns a dropped response
    /// plus a naive retry into a second purchase, because the second attempt would carry a second identity.
    /// </remarks>
    public static readonly HttpRequestOptionsKey<Guid> IdempotencyKey = new("anis.partners.idempotency-key");
}
