// <auto-generated>
//     Generated from contracts/error-catalogue.json by tools/generate-errors.py.
//     Do not edit. Run the generator; the drift test fails if this file and the catalogue disagree.
// </auto-generated>

#nullable enable

namespace Anis.Partners.Sdk.Errors;

/// <summary>Every public error code the Anis Partner API can return.</summary>
/// <remarks>
/// <c>code</c> is the machine contract. <c>title</c> and <c>detail</c> are localized presentation and must
/// never drive branching -- they change with Accept-Language and with copy edits.
/// </remarks>
public enum PartnerErrorCode
{
    /// <summary>A code this SDK version does not know. Read <see cref="AnisApiException.RawCode"/>.</summary>
    Unknown = 0,

    /// <summary>HTTP 403. Confirm or re-enable the owner account before making a new request.</summary>
    AccountInactive = 1,

    /// <summary>HTTP 402. Submit a new operation with explicit allowed-debt consent if the Partner intends to use debt.</summary>
    AllowedDebtConsentRequired = 2,

    /// <summary>HTTP 403. Restore the directly owned active account and Business subscription before making a new request.</summary>
    BindingNotAuthorized = 3,

    /// <summary>HTTP 409. Restore an active Business subscription before making a new request.</summary>
    BusinessSubscriptionRequired = 4,

    /// <summary>HTTP 404. Verify the sold-card identifier and wallet; absent and inaccessible single cards return the same representation.</summary>
    CardNotFound = 5,

    /// <summary>HTTP 409. Refresh Catalogue data and submit a new operation if the item becomes available.</summary>
    CardUnavailable = 6,

    /// <summary>HTTP 409. Restart enrollment through the approved staff action and use the new challenge generation.</summary>
    ChallengeExpired = 7,

    /// <summary>HTTP 422. Use the currency required by the authoritative wallet and Catalogue contract.</summary>
    CurrencyNotSupported = 8,

    /// <summary>HTTP 429. No reset time is available; submit a new operation and idempotency key only after the limit condition is known to have cleared.</summary>
    DailyLimitExceeded = 9,

    /// <summary>HTTP 503, retryable. Retry with the same idempotency key for the same mutation intent after bounded backoff.</summary>
    DependencyUnavailable = 10,

    /// <summary>HTTP 409. Reuse the key only for identical intent; use a new UUID only for a genuinely new operation.</summary>
    IdempotencyConflict = 11,

    /// <summary>HTTP 409. Submit a new operation only after the authoritative balance or allowed-debt state changes.</summary>
    InsufficientBalance = 12,

    /// <summary>HTTP 403. The application is not permitted to make this call: check that it holds the permission the call needs and that you call from a network agreed with Anis, then ask Anis staff to change either.</summary>
    InsufficientScope = 13,

    /// <summary>HTTP 500, retryable. Preserve the same accepted operation and idempotency key; retry only after bounded backoff or platform remediation.</summary>
    InternalError = 14,

    /// <summary>HTTP 400. Reserved: the current API never sends this code. A Content-Digest that does not match the body is answered malformed_signed_request (400).</summary>
    InvalidContentDigest = 15,

    /// <summary>HTTP 401. Correct the signing credentials or profile before retrying; key and application state details are intentionally indistinguishable.</summary>
    InvalidCredentials = 16,

    /// <summary>HTTP 401. Obtain a new enrollment invitation through the approved staff process.</summary>
    InvitationInvalid = 17,

    /// <summary>HTTP 409. Use individual reveal for selected cards; invoice reveal is capped at 100.</summary>
    InvoiceRevealLimitExceeded = 18,

    /// <summary>HTTP 409. This invitation already took a key, so a newly generated key pair is refused too. Read the enrolment status first; to enrol a different key, ask Anis staff to restart the enrolment.</summary>
    KeyDuplicate = 19,

    /// <summary>HTTP 422. Correct the P-256/P1363 proof for the active challenge generation.</summary>
    KeyProofInvalid = 20,

    /// <summary>HTTP 400. Rebuild how the request is signed: send both Signature and Signature-Input, cover the required components in the documented order, send every header the route requires, and compute Content-Digest over the exact body bytes. Repeating the same request unchanged fails the same way.</summary>
    MalformedSignedRequest = 37,

    /// <summary>HTTP 202, retryable. Not an error: the order was accepted and is still being processed. Wait for the Retry-After delay, then repeat the identical POST with the same Idempotency-Key.</summary>
    OperationProcessing = 21,

    /// <summary>HTTP 409. Do not poll; submit a new operation and idempotency key only after the owner allowance is known to have changed.</summary>
    OwnerLimitExceeded = 22,

    /// <summary>HTTP 409. Refresh the current price and explicitly accept it in a new operation.</summary>
    PriceChanged = 23,

    /// <summary>HTTP 403. The owner policy forbids this purchase; obtain authorization before submitting a new operation.</summary>
    PurchaseNotAllowed = 24,

    /// <summary>HTTP 409. Refresh Catalogue data or submit a new operation with an available quantity.</summary>
    QuantityUnavailable = 25,

    /// <summary>HTTP 429, retryable. honour Retry-After when present; otherwise use bounded exponential backoff.</summary>
    RateLimited = 26,

    /// <summary>HTTP 409, retryable. Use a fresh nonce and signature while preserving the idempotency key for the same business intent.</summary>
    ReplayDetected = 27,

    /// <summary>HTTP 504, retryable. Inspect operation status or repeat the identical request with the same idempotency key.</summary>
    RequestTimeout = 28,

    /// <summary>HTTP 404. Verify the resource identifier and application ownership; inaccessible resources are intentionally indistinguishable from absence.</summary>
    ResourceNotFound = 29,

    /// <summary>HTTP 409. The card-level reveal predicate refused disclosure; do not retry until the card state is known to have changed.</summary>
    RevealNotAllowed = 30,

    /// <summary>HTTP 401, retryable. Reserved: the current API never sends this code. A signature outside its validity window is answered invalid_credentials (401); sign again with current timestamps.</summary>
    SignatureExpired = 31,

    /// <summary>HTTP 403. Anis network protection blocked this source address. Contact Anis support with the address if it should be allowed.</summary>
    SourceIpNotAllowed = 32,

    /// <summary>HTTP 422. The response never names the field: check the request against the documented rules before sending it again. How the request is sent counts too: a body over 64 KB, a chunked body (send Content-Length instead), headers over 32 KB in total, a path and query over 2,048 characters, a body on a call that takes none, or an order whose Idempotency-Key is missing or is not a UUID written with hyphens.</summary>
    ValidationFailed = 33,

    /// <summary>HTTP 409. Submit a new request only after the wallet has been re-enabled.</summary>
    WalletDisabled = 34,

    /// <summary>HTTP 409. Submit a new request only after the account or Business subscription expiry is resolved.</summary>
    WalletExpired = 35,

    /// <summary>HTTP 404. Obtain an approved current wallet grant before making a new request.</summary>
    WalletNotGranted = 36,
}

/// <summary>Maps between the wire code and <see cref="PartnerErrorCode"/>, and reports retryability.</summary>
public static class PartnerErrorCodes
{
    private static readonly Dictionary<string, PartnerErrorCode> ByWire = new(StringComparer.Ordinal)
    {
        ["account_inactive"] = PartnerErrorCode.AccountInactive,
        ["allowed_debt_consent_required"] = PartnerErrorCode.AllowedDebtConsentRequired,
        ["binding_not_authorized"] = PartnerErrorCode.BindingNotAuthorized,
        ["business_subscription_required"] = PartnerErrorCode.BusinessSubscriptionRequired,
        ["card_not_found"] = PartnerErrorCode.CardNotFound,
        ["card_unavailable"] = PartnerErrorCode.CardUnavailable,
        ["challenge_expired"] = PartnerErrorCode.ChallengeExpired,
        ["currency_not_supported"] = PartnerErrorCode.CurrencyNotSupported,
        ["daily_limit_exceeded"] = PartnerErrorCode.DailyLimitExceeded,
        ["dependency_unavailable"] = PartnerErrorCode.DependencyUnavailable,
        ["idempotency_conflict"] = PartnerErrorCode.IdempotencyConflict,
        ["insufficient_balance"] = PartnerErrorCode.InsufficientBalance,
        ["insufficient_scope"] = PartnerErrorCode.InsufficientScope,
        ["internal_error"] = PartnerErrorCode.InternalError,
        ["invalid_content_digest"] = PartnerErrorCode.InvalidContentDigest,
        ["invalid_credentials"] = PartnerErrorCode.InvalidCredentials,
        ["invitation_invalid"] = PartnerErrorCode.InvitationInvalid,
        ["invoice_reveal_limit_exceeded"] = PartnerErrorCode.InvoiceRevealLimitExceeded,
        ["key_duplicate"] = PartnerErrorCode.KeyDuplicate,
        ["key_proof_invalid"] = PartnerErrorCode.KeyProofInvalid,
        ["malformed_signed_request"] = PartnerErrorCode.MalformedSignedRequest,
        ["operation_processing"] = PartnerErrorCode.OperationProcessing,
        ["owner_limit_exceeded"] = PartnerErrorCode.OwnerLimitExceeded,
        ["price_changed"] = PartnerErrorCode.PriceChanged,
        ["purchase_not_allowed"] = PartnerErrorCode.PurchaseNotAllowed,
        ["quantity_unavailable"] = PartnerErrorCode.QuantityUnavailable,
        ["rate_limited"] = PartnerErrorCode.RateLimited,
        ["replay_detected"] = PartnerErrorCode.ReplayDetected,
        ["request_timeout"] = PartnerErrorCode.RequestTimeout,
        ["resource_not_found"] = PartnerErrorCode.ResourceNotFound,
        ["reveal_not_allowed"] = PartnerErrorCode.RevealNotAllowed,
        ["signature_expired"] = PartnerErrorCode.SignatureExpired,
        ["source_ip_not_allowed"] = PartnerErrorCode.SourceIpNotAllowed,
        ["validation_failed"] = PartnerErrorCode.ValidationFailed,
        ["wallet_disabled"] = PartnerErrorCode.WalletDisabled,
        ["wallet_expired"] = PartnerErrorCode.WalletExpired,
        ["wallet_not_granted"] = PartnerErrorCode.WalletNotGranted,
    };

    private static readonly HashSet<PartnerErrorCode> Retryable =
    [
        PartnerErrorCode.DependencyUnavailable,
        PartnerErrorCode.InternalError,
        PartnerErrorCode.OperationProcessing,
        PartnerErrorCode.RateLimited,
        PartnerErrorCode.ReplayDetected,
        PartnerErrorCode.RequestTimeout,
        PartnerErrorCode.SignatureExpired,
    ];

    /// <summary>The wire spelling of every known code.</summary>
    public static IReadOnlyCollection<string> All => ByWire.Keys;

    /// <summary>Resolves a wire code, or <see cref="PartnerErrorCode.Unknown"/>.</summary>
    public static PartnerErrorCode Parse(string? code)
        => code is not null && ByWire.TryGetValue(code, out var value) ? value : PartnerErrorCode.Unknown;

    /// <summary>Whether the catalogue marks this code retryable. An unknown code is never assumed to be.</summary>
    public static bool IsRetryable(PartnerErrorCode code) => Retryable.Contains(code);
}
