"""Generates the error surface from contracts/error-catalogue.json.

Run:  python3 tools/generate-errors.py

The catalogue names "sdk-constants" as one of its own generation targets, so this is the intended
direction: the catalogue is the source and the C# is the output. Never edit the generated file -- a hand
edit is a divergence from the contract that the drift test will then fail on.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAT = os.path.join(ROOT, "contracts", "error-catalogue.json")
OUT = os.path.join(ROOT, "src", "Anis.Partners.Sdk", "Errors", "PartnerErrors.g.cs")


def pascal(code):
    return "".join(p.capitalize() for p in code.split("_"))


catalogue = json.load(open(CAT))
public = [r for r in catalogue["representations"] if r.get("publicDocumentation")]
# (publicCode, httpStatus) is the catalogue's own representation key; the same code can appear on two
# statuses, so the enum is keyed on the code and the status travels on the exception.
seen, codes = set(), []
for r in sorted(public, key=lambda r: r["publicCode"]):
    if r["publicCode"] not in seen:
        seen.add(r["publicCode"])
        codes.append(r)

lines = []
w = lines.append
w("// <auto-generated>")
w("//     Generated from contracts/error-catalogue.json by tools/generate-errors.py.")
w("//     Do not edit. Run the generator; the drift test fails if this file and the catalogue disagree.")
w("// </auto-generated>")
w("")
# Generated files opt out of the project's nullable context unless they say otherwise.
w("#nullable enable")
w("")
w("namespace Anis.Partners.Sdk.Errors;")
w("")
w("/// <summary>Every public error code the Anis Partner API can return.</summary>")
w("/// <remarks>")
w("/// <c>code</c> is the machine contract. <c>title</c> and <c>detail</c> are localized presentation and must")
w("/// never drive branching -- they change with Accept-Language and with copy edits.")
w("/// </remarks>")
w("public enum PartnerErrorCode")
w("{")
w("    /// <summary>A code this SDK version does not know. Read <see cref=\"AnisApiException.RawCode\"/>.</summary>")
w("    Unknown = 0,")
for i, r in enumerate(codes, start=1):
    w("")
    guidance = r.get("retryGuidance", "").replace("<", "&lt;").replace(">", "&gt;")
    w(f"    /// <summary>HTTP {r['httpStatus']}{', retryable' if r.get('retryable') else ''}. {guidance}</summary>")
    w(f"    {pascal(r['publicCode'])} = {i},")
w("}")
w("")
w("/// <summary>Maps between the wire code and <see cref=\"PartnerErrorCode\"/>, and reports retryability.</summary>")
w("public static class PartnerErrorCodes")
w("{")
w("    private static readonly Dictionary<string, PartnerErrorCode> ByWire = new(StringComparer.Ordinal)")
w("    {")
for r in codes:
    w(f"        [\"{r['publicCode']}\"] = PartnerErrorCode.{pascal(r['publicCode'])},")
w("    };")
w("")
w("    private static readonly HashSet<PartnerErrorCode> Retryable =")
w("    [")
for r in codes:
    if r.get("retryable"):
        w(f"        PartnerErrorCode.{pascal(r['publicCode'])},")
w("    ];")
w("")
w("    /// <summary>The wire spelling of every known code.</summary>")
w("    public static IReadOnlyCollection<string> All => ByWire.Keys;")
w("")
w("    /// <summary>Resolves a wire code, or <see cref=\"PartnerErrorCode.Unknown\"/>.</summary>")
w("    public static PartnerErrorCode Parse(string? code)")
w("        => code is not null && ByWire.TryGetValue(code, out var value) ? value : PartnerErrorCode.Unknown;")
w("")
w("    /// <summary>Whether the catalogue marks this code retryable. An unknown code is never assumed to be.</summary>")
w("    public static bool IsRetryable(PartnerErrorCode code) => Retryable.Contains(code);")
w("}")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(lines) + "\n")
print(f"generated {len(codes)} public codes -> {os.path.relpath(OUT, ROOT)}")
